--autogenerated by SqlConstantsGenerator v1.0.0.0

create view [MsBuildTestConstants]
with schemabinding
as
select
	??? as BirthDate,
	'John' as FirstName,
	'Snow' as LastName,
	'Pizza' as FavFood,
	12345 as FavNumber
;
go