--autogenerated by SqlConstantsGenerator v1.0.0.0

if(object_id(N'[MsBuildTestConstants]', N'V') is not null) drop view [MsBuildTestConstants];
go

create view [MsBuildTestConstants]
with schemabinding
as
select
	convert(datetime, '2000-01-01 18:35:40', 120) as BirthDate,
	'John' as FirstName,
	'Snow' as LastName,
	'Pizza' as FavFood,
	12345 as FavNumber
;
go

print 'View [MsBuildTestConstants] created successfully.';
go